name: Generate and Deploy to Github Pages
permissions:
  contents: write
on:
  push:
    branches:
      - nuxt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install and Build
        run: npm install && npm run generate

      - name: Extra Files
        run: |
          # Switch to the generated directory
          cd .output/public

          # Set custom domain for GitHub Pages
          echo "phphe.com" > CNAME

          # Required to bypass Jekyll on GitHub Pages
          echo "" > .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          single-commit: true
          branch: gh-pages
          clean: true
          folder: .output/public
